### ISSUE TITLE
SEGV caused by a READ memory access

### ISSUE THREAD

**Issue by Cvjark** [Moodstocks/jpec#5]
hi, i compile this repo with ASAN to do some test, after compiling I feed test.png in this repo and it crash.
compile command: `AFL_USE_ASAN=1 make  CC=afl-clang-fast LDFLAGS="-lopencv"`

and here is the crash info: 
```
AddressSanitizer:DEADLYSIGNAL

==110236==ERROR: AddressSanitizer: SEGV on unknown address 0x000000001c78 (pc 0x0000004f4d2e bp 0x7ffeb85f5cd0 sp 0x7ffeb85f5bc0 T0)
==110236==The signal is caused by a READ memory access.
    #0 0x4f4d2e in load_image /home/bupt/Desktop/jpec/main.c:69:22
    #1 0x4f49b0 in main /home/bupt/Desktop/jpec/main.c:46:20
    #2 0x7ff2c275bc86 in __libc_start_main /build/glibc-CVJwZb/glibc-2.27/csu/../csu/libc-start.c:310
    #3 0x41c759 in _start (/home/bupt/Desktop/jpec/jpec+0x41c759)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/bupt/Desktop/jpec/main.c:69:22 in load_image
==110236==ABORTING
```
command to reproduce the crash: `./jpec test.png`
[test.zip](https://github.com/Moodstocks/jpec/files/9016905/test.zip)

### is it some kind of bug?

**Comment by catwell** [comment]
I don't think anyone is maintaining this anymore, but this looks like an OpenCV version issue. `main.c` expects OpenCV which is quite old and maybe not the one you are linking. This issue should not affect the lib itself, which does not rely on OpenCV (only `main.c` does).
